###
GET http://localhost:8080/test


### Create Account
POST http://localhost:8080/register
Content-Type: application/json

{
  "account": "testAccount1",
  "password": "TestPassword1"
}

### Unknown Path
POST http://localhost:8080/Login


### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "account": "testAccount1",
  "password": "TestPassword1"
}

### Create Schedule
POST http://localhost:8080/
Cookie: JSESSIONID=C2D734CF4F0BA8116BBE4AB0C5D1785E
Content-Type: application/json

{
  "title": "title!",
  "detail": "detail text",
  "startAt": "2025-04-05T00:00:00",
  "endAt": "2025-04-07T00:00:00"

}





