###
GET http://localhost:8080/1
Accept: */*


### Create Test
POST http://localhost:8080
Content-Type: application/json

{
  "writer": "Mr.N",
  "password": "p1",
  "title": "title!",
  "memo": "",
  "startTime": 1742829690000,
  "endTime": 1742829690000

}


### Get List
GET http://localhost:8080/list

### Get List Options 1
GET http://localhost:8080/list?writer=Lee

### Patch Schedule
PATCH http://localhost:8080/
Content-Type: application/json

{
  "no": 99,
  "password": "p1q",
  "writer": "Mrs. aJ",
  "title": "Schedule Name",
  "memo": "This! Is! Test!"
}

### Delete Schedule
DELETE http://localhost:8080/
Content-Type: application/json

{
  "no": 11,
  "password": "p1"
}

