###
GET http://localhost:8080/test


### Create Account
POST http://localhost:8080/register
Content-Type: application/json

{
  "account": "testAccount1",
  "password": "TestPassword1"
}

### Unknown Path
POST http://localhost:8080/Login


### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "account": "testAccount1",
  "password": "TestPassword1"
}

### Create Test
POST http://localhost:8080
Authorization:
Content-Type: application/json

{
  "writer": "Mr.N",
  "password": "p1",
  "title": "title!",
  "memo": "",
  "startTime": 1742829690000,
  "endTime": 1742829690000

}





